<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MB16O9P" name="api" tests="2" failures="2" timestamp="24 Aug 2017 10:20:26 GMT" time="2.216" errors="0">
  <testcase name="negativeNumber" time="0.069" classname="com.zzkg.cases.gift.ExchangeGift">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at common.ReadExcel.getExchangeGiftApi(ReadExcel.java:142)
	at datapro.GetApi.exchangeGiftApi(GetApi.java:10)
	at com.zzkg.cases.gift.ExchangeGift.negativeNumber(ExchangeGift.java:30)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- negativeNumber -->
  <testcase name="zeroNumber" time="0.459" classname="com.zzkg.cases.gift.ExchangeGift">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.zzkg.cases.gift.ExchangeGift.zeroNumber(ExchangeGift.java:53)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- zeroNumber -->
</testsuite> <!-- api -->
